apiVersion: apps/v1
kind: Deployment
metadata:
  name: irclogbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logbot
  template:
    metadata:
      labels:
        app: logbot
    spec:
      containers:
      - name: logbot-0
        image: edleafe/irclogbot:latest
        ports:
        - containerPort: 80
          name: http
        - containerPort: 6667
          name: irc
        - containerPort: 9200
          name: elastic
        securityContext:
          privileged: true
        command: ["python", "irclogbot.py", "-f", "channels.txt", "-s", "0"]
      - name: logbot-1
        image: edleafe/irclogbot:latest
        ports:
        - containerPort: 80
          name: http
        - containerPort: 6667
          name: irc
        - containerPort: 9200
          name: elastic
        securityContext:
          privileged: true
        command: ["python", "irclogbot.py", "-f", "channels.txt", "-s", "1"]
      - name: logbot-2
        image: edleafe/irclogbot:latest
        ports:
        - containerPort: 80
          name: http
        - containerPort: 6667
          name: irc
        - containerPort: 9200
          name: elastic
        securityContext:
          privileged: true
        command: ["python", "irclogbot.py", "-f", "channels.txt", "-s", "2"]
      - name: logbot-3
        image: edleafe/irclogbot:latest
        ports:
        - containerPort: 80
          name: http
        - containerPort: 6667
          name: irc
        - containerPort: 9200
          name: elastic
        securityContext:
          privileged: true
        command: ["python", "irclogbot.py", "-f", "channels.txt", "-s", "3"]
      - name: logbot-4
        image: edleafe/irclogbot:latest
        ports:
        - containerPort: 80
          name: http
        - containerPort: 6667
          name: irc
        - containerPort: 9200
          name: elastic
        securityContext:
          privileged: true
        command: ["python", "irclogbot.py", "-f", "channels.txt", "-s", "4"]
      - name: logbot-5
        image: edleafe/irclogbot:latest
        ports:
        - containerPort: 80
          name: http
        - containerPort: 6667
          name: irc
        - containerPort: 9200
          name: elastic
        securityContext:
          privileged: true
        command: ["python", "irclogbot.py", "-f", "channels.txt", "-s", "5"]
      - name: logbot-6
        image: edleafe/irclogbot:latest
        ports:
        - containerPort: 80
          name: http
        - containerPort: 6667
          name: irc
        - containerPort: 9200
          name: elastic
        securityContext:
          privileged: true
        command: ["python", "irclogbot.py", "-f", "channels.txt", "-s", "6"]
      - name: logbot-7
        image: edleafe/irclogbot:latest
        ports:
        - containerPort: 80
          name: http
        - containerPort: 6667
          name: irc
        - containerPort: 9200
          name: elastic
        securityContext:
          privileged: true
        command: ["python", "irclogbot.py", "-f", "channels.txt", "-s", "7"]
      - name: logbot-8
        image: edleafe/irclogbot:latest
        ports:
        - containerPort: 80
          name: http
        - containerPort: 6667
          name: irc
        - containerPort: 9200
          name: elastic
        securityContext:
          privileged: true
        command: ["python", "irclogbot.py", "-f", "channels.txt", "-s", "8"]
