apiVersion: apps/v1
kind: Deployment
metadata:
  name: irclogbot1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logbot
  minReadySeconds: 5
  strategy:
    # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: logbot
    spec:
      containers:
      - name: logbot-1
        image: edleafe/irclogbot:v1.16
        ports:
        - containerPort: 80
          name: http
        - containerPort: 6667
          name: irc
        - containerPort: 9200
          name: elastic
        securityContext:
          privileged: false
        command: ["python", "-u", "irclogbot.py", "-f", "channels.txt", "-s", "1"]
        readinessProbe:
          exec:
            command:
              - python
              - filemod_check.py
          initialDelaySeconds: 60
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
              - python
              - filemod_check.py
          initialDelaySeconds: 60
          periodSeconds: 180
